version: 0.1

phases:
  install:
    commands:
      - bundle install
  pre_build:
    commands:
      - echo Do nothing
  build:
    commands:
      - echo Build started on `date`
      - rake
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./**
