version: 0.1

phases:
  install:
    commands:
      - echo Do nothing
  pre_build:
    commands:
      - printenv
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./**
